// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavbhPzeanlXcRzw8AQc1aeTZ8i8JdlTo',
    appId: '1:634654633264:web:a1bcad8d3169452b316cf5',
    messagingSenderId: '634654633264',
    projectId: 'finance-guardian-453af',
    authDomain: 'finance-guardian-453af.firebaseapp.com',
    storageBucket: 'finance-guardian-453af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTnbZ9uMpc9CmFCdP_sdLdpg6_WjrApA',
    appId: '1:634654633264:android:18bd9043f6d695ed316cf5',
    messagingSenderId: '634654633264',
    projectId: 'finance-guardian-453af',
    storageBucket: 'finance-guardian-453af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC5GZwWNAFpUKeNza48h4ISCvLEI-m1JE',
    appId: '1:634654633264:ios:d4c2cc66b65bfbca316cf5',
    messagingSenderId: '634654633264',
    projectId: 'finance-guardian-453af',
    storageBucket: 'finance-guardian-453af.firebasestorage.app',
    iosBundleId: 'com.kavita.financeguardian.financeGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC5GZwWNAFpUKeNza48h4ISCvLEI-m1JE',
    appId: '1:634654633264:ios:d4c2cc66b65bfbca316cf5',
    messagingSenderId: '634654633264',
    projectId: 'finance-guardian-453af',
    storageBucket: 'finance-guardian-453af.firebasestorage.app',
    iosBundleId: 'com.kavita.financeguardian.financeGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAavbhPzeanlXcRzw8AQc1aeTZ8i8JdlTo',
    appId: '1:634654633264:web:e10079b462f454fd316cf5',
    messagingSenderId: '634654633264',
    projectId: 'finance-guardian-453af',
    authDomain: 'finance-guardian-453af.firebaseapp.com',
    storageBucket: 'finance-guardian-453af.firebasestorage.app',
  );
}
